FROM mcr.microsoft.com/dotnet/sdk:7.0

# Install required tools and libraries
RUN apt-get update && \
    apt-get install -y wget unzip lib32stdc++6 lib32z1 git openjdk-11-jdk && \
    apt-get clean

# Set Java environment
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin

# Define Android SDK versions
ENV ANDROID_SDK_ROOT /root/Android/Sdk
ENV PATH $PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
ENV USER UserName
ENV USERNAME UserName
ENV LOGNAME UserName

# Install Android SDK command line tools
#RUN mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools && \
RUN mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip 
RUN unzip commandlinetools-linux-7302050_latest.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools
RUN mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest 
RUN rm commandlinetools-linux-7302050_latest.zip

RUN yes | sdkmanager --licenses
#sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
#sdkmanager "platforms;android-33" "build-tools;33.0.0"
RUN sdkmanager --install "platforms;android-33"
RUN sdkmanager --install "build-tools;33.0.0" 
RUN sdkmanager --install "platform-tools"
RUN sdkmanager --install "cmdline-tools;7.0"

RUN dotnet workload install maui-android 
RUN dotnet workload install maui-tizen
RUN dotnet workload install maui-windows