FROM androidsdk/android-31:latest

RUN apt-get update
RUN wget https://dot.net/v1/dotnet-install.sh
RUN chmod +x ./dotnet-install.sh
RUN ./dotnet-install.sh -c 7.0

ENV PATH $PATH:~/.dotnet
#RUN dotnet workload install maui-android 
#RUN dotnet workload install maui-tizen
#RUN dotnet workload install maui-windows