# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: MBSChat
  PYTHON_VERSION: '3.10'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: az --version
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pytest

    - name: App Service Web App Build Action
      uses: Azure/appservice-build@v3
#      with:
        # 'Relative path (within the repository) to the source directory of the project you want to build; if no value is provided for this, the root of the repository ("GITHUB_WORKSPACE" environment variable) will be built.'

#        source-directory: # optional
        # 'Programming platform used to build the web app; if no value is provided, Oryx will determine the platform to build with. Supported values: dotnet, golang, java, nodejs, php, python, ruby'
        
#        platform: # optional
        # 'Version of the programming platform used to build the web app; if no value is provided, Oryx will determine the version needed to build the repository.'

#        platform-version: # optional
        # The directory where the build output will be copied to.        
#        output-directory: # optional
       
          
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'MBSChat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}    
        

